namess = {
    'john': 'johnny',
    'emily': 'emi',
    'michael': 'mike',
    'jessica': 'jess',
    'william': 'will',
    'alexandra': 'alex',
    'daniel': 'dan',
    'olivia': 'liv',
    'benjamin': 'ben',
    'sophia': 'sophie',
    'noe': 'nono',
    'jules': 'jul',
    'july': 'juju',
    'adam': 'ade',
    'adrian': 'adri',
    'aiden': 'aid',
    'alexander': 'alex',
    'amanda': 'mandy',
    'amelia': 'meli',
    'anna': 'annie',
    'anthony': 'tony',
    'ashley': 'ash',
    'aubrey': 'bree',
    'audrey': 'aud',
    'ava': 'avie',
    'brian': 'bri',
    'caleb': 'cay',
    'cameron': 'cam',
    'charles': 'charlie',
    'chloe': 'clo',
    'christopher': 'chris',
    'claire': 'clai',
    'david': 'dave',
    'dylan': 'dyl',
    'elijah': 'eli',
    'ella': 'elle',
    'ethan': 'eth',
    'eva': 'eve',
    'evan': 'ev',
    'grace': 'gracie',
    'gabriel': 'gabi',
    'hannah': 'han',
    'harrison': 'harry',
    'henry': 'hank',
    'isabella': 'bella',
    'isaac': 'ike',
    'jack': 'jackie',
    'jacob': 'jake',
    'jackson': 'jack',
    'james': 'jimmy',
    'jayden': 'jay',
    'jennifer': 'jen',
    'jeremy': 'jerry',
    'johnny': 'jon',
    'joseph': 'joe',
    'julia': 'jules',
    'justin': 'jay',
    'katherine': 'kat',
    'kevin': 'vin',
    'lauren': 'laurie',
    'liam': 'lee',
    'lillian': 'lily',
    'lily': 'lils',
    'lucas': 'luke',
    'lucy': 'lulu',
    'mason': 'mace',
    'matthew': 'matt',
    'mia': 'mimi',
    'nathan': 'nate',
    'nathaniel': 'nathan',
    'natalie': 'nat',
    'nicholas': 'nick',
    'noah' or 'noa': 'nono',
    'oliver': 'oliv',
    'owen': 'ow',
    'peter': 'pete',
    'rachel': 'rach',
    'rebecca': 'becky',
    'richard': 'ricky',
    'robert': 'rob',
    'ryan': 'ry',
    'samuel': 'samy',
    'samantha': 'sam',
    'sebastian': 'seb',
    'sophie': 'soso',
    'steven': 'steve',
    'thomas': 'tommy',
    'victoria': 'vicky',
    'william': 'willie',
    'zachary': 'zac',
    'neyox': 'neo',
    'track': 'tom',
    'trax': 'tom',
    'fifi': 'philippe',
    'phoebe': 'bee',
    'brandon': 'brad'
}


async def find_name(email: str):
    username = email.split("@")[0]
    founds = 0

    for fname, pseudo in namess.items():
        if username in pseudo:
            founds += 1
            print("\n[+] Name found => " +  fname)

    if founds == 0:
        print("\n[-] Name not found for this username.")
    
